### PR TITLE
Adding SQL commands as well as comments about special characters.

### PR DESCRIPTION
**Pull request by grainme**

### CODE REVIEW

**Review by grainme — COMMENTED** [review]
adding interactive quiz ?

**Comment by felixoakz** [comment]
You mean adding an input so the users can add the commands themselves??

**Comment by grainme** [comment]
No, I mean adding another tab called "Quiz" on which users can test their knowledge on a specific subject (git, sql...)

**Comment by felixoakz** [comment]
Oh yeah, that can be a nice adding! I will write it down on read me and start thinking about how to implement it. Feel free to add anything you find interesting as well :)

**Comment by grainme** [comment]
Okay Great, Thanks!

**Pull request merged**
